name: CI
on: [push, pull_request]

jobs:
    lua-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: leafo/gh-actions-lua@v8
            - uses: leafo/gh-actions-luarocks@v4
            - run: luarocks install luacheck
            - run: luacheck -g --codes *.lua **/*.lua
    js-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm i
            - run: npx eslint nui/js
